branch-defaults:
  '1.0':
    environment: null
    group_suffix: null
global:
  application_name: sr_tracker
  branch: '1.0'
  default_ec2_keyname: sr-tracker
  default_platform: Python 3.4 (Preconfigured - Docker)
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: SR_Tracker
  sc: git
  workspace_type: Application
